version: '3'

networks:
  network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16

services:
  namenode:
    image: hadoop
    volumes:
      - ./etc/hosts:/etc/hosts
      - ./hadoop:/hadoop
    ports:
      - 9000:9000
    networks:
      network:
        ipv4_address: 172.20.0.2
    hostname: namenode

  datanode1:
    image: hadoop
    volumes:
      - ./hadoop:/hadoop
    networks:
      network:
        ipv4_address: 172.20.0.3
    hostname: datanode1
  
  datanode2:
    image: hadoop
    volumes:
      - ./hadoop:/hadoop
    networks:
      network:
        ipv4_address: 172.20.0.4
    hostname: datanode2
